/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { FormFillRequestOptionsFieldsItem } from "./FormFillRequestOptionsFieldsItem";

export const FormFillRequestOptions: core.serialization.ObjectSchema<
    serializers.pdf.FormFillRequestOptions.Raw,
    Fileforge.pdf.FormFillRequestOptions
> = core.serialization.object({
    fields: core.serialization.list(FormFillRequestOptionsFieldsItem),
});

export declare namespace FormFillRequestOptions {
    interface Raw {
        fields: FormFillRequestOptionsFieldsItem.Raw[];
    }
}
