/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormDetectRequestOptions: core.serialization.ObjectSchema<
    serializers.pdf.FormDetectRequestOptions.Raw,
    Fileforge.pdf.FormDetectRequestOptions
> = core.serialization.object({});

export declare namespace FormDetectRequestOptions {
    interface Raw {}
}
