/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormMarkRequestOptions: core.serialization.ObjectSchema<
    serializers.pdf.FormMarkRequestOptions.Raw,
    Fileforge.pdf.FormMarkRequestOptions
> = core.serialization.object({});

export declare namespace FormMarkRequestOptions {
    interface Raw {}
}
