/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormFillRequestOptionsFieldsItemThree: core.serialization.ObjectSchema<
    serializers.pdf.FormFillRequestOptionsFieldsItemThree.Raw,
    Fileforge.pdf.FormFillRequestOptionsFieldsItemThree
> = core.serialization.object({
    name: core.serialization.string(),
    type: core.serialization.stringLiteral("PDFRadioGroup"),
    selected: core.serialization.string(),
});

export declare namespace FormFillRequestOptionsFieldsItemThree {
    interface Raw {
        name: string;
        type: "PDFRadioGroup";
        selected: string;
    }
}
