/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { FormDetectResponseItemIsEditableType } from "./FormDetectResponseItemIsEditableType";

export const FormDetectResponseItemIsEditable: core.serialization.ObjectSchema<
    serializers.pdf.FormDetectResponseItemIsEditable.Raw,
    Fileforge.pdf.FormDetectResponseItemIsEditable
> = core.serialization.object({
    type: FormDetectResponseItemIsEditableType,
    options: core.serialization.list(core.serialization.string()).optional(),
    isMultiselect: core.serialization.boolean().optional(),
    selected: core.serialization.list(core.serialization.string()).optional(),
    isEditable: core.serialization.boolean().optional(),
});

export declare namespace FormDetectResponseItemIsEditable {
    interface Raw {
        type: FormDetectResponseItemIsEditableType.Raw;
        options?: string[] | null;
        isMultiselect?: boolean | null;
        selected?: string[] | null;
        isEditable?: boolean | null;
    }
}
