/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormDetectResponseItemIsChecked: core.serialization.ObjectSchema<
    serializers.pdf.FormDetectResponseItemIsChecked.Raw,
    Fileforge.pdf.FormDetectResponseItemIsChecked
> = core.serialization.object({
    type: core.serialization.stringLiteral("PDFCheckBox"),
    isChecked: core.serialization.boolean().optional(),
});

export declare namespace FormDetectResponseItemIsChecked {
    interface Raw {
        type: "PDFCheckBox";
        isChecked?: boolean | null;
    }
}
