/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormFillRequestOptionsFieldsItemTwoType: core.serialization.Schema<
    serializers.pdf.FormFillRequestOptionsFieldsItemTwoType.Raw,
    Fileforge.pdf.FormFillRequestOptionsFieldsItemTwoType
> = core.serialization.enum_(["PDFOptionList", "PDFDropdown"]);

export declare namespace FormFillRequestOptionsFieldsItemTwoType {
    type Raw = "PDFOptionList" | "PDFDropdown";
}
