/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormDetectRequestOptionsAiDetection: core.serialization.ObjectSchema<
    serializers.pdf.FormDetectRequestOptionsAiDetection.Raw,
    Fileforge.pdf.FormDetectRequestOptionsAiDetection
> = core.serialization.object({
    enable: core.serialization.boolean().optional(),
    limit: core.serialization.number().optional(),
});

export declare namespace FormDetectRequestOptionsAiDetection {
    interface Raw {
        enable?: boolean | null;
        limit?: number | null;
    }
}
