/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { FormFillRequestOptionsFieldsItemValue } from "./FormFillRequestOptionsFieldsItemValue";
import { FormFillRequestOptionsFieldsItemChecked } from "./FormFillRequestOptionsFieldsItemChecked";
import { FormFillRequestOptionsFieldsItemTwo } from "./FormFillRequestOptionsFieldsItemTwo";
import { FormFillRequestOptionsFieldsItemThree } from "./FormFillRequestOptionsFieldsItemThree";

export const FormFillRequestOptionsFieldsItem: core.serialization.Schema<
    serializers.pdf.FormFillRequestOptionsFieldsItem.Raw,
    Fileforge.pdf.FormFillRequestOptionsFieldsItem
> = core.serialization.undiscriminatedUnion([
    FormFillRequestOptionsFieldsItemValue,
    FormFillRequestOptionsFieldsItemChecked,
    FormFillRequestOptionsFieldsItemTwo,
    FormFillRequestOptionsFieldsItemThree,
]);

export declare namespace FormFillRequestOptionsFieldsItem {
    type Raw =
        | FormFillRequestOptionsFieldsItemValue.Raw
        | FormFillRequestOptionsFieldsItemChecked.Raw
        | FormFillRequestOptionsFieldsItemTwo.Raw
        | FormFillRequestOptionsFieldsItemThree.Raw;
}
