/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const FormDetectResponseItemDefaultValue: core.serialization.ObjectSchema<
    serializers.pdf.FormDetectResponseItemDefaultValue.Raw,
    Fileforge.pdf.FormDetectResponseItemDefaultValue
> = core.serialization.object({
    type: core.serialization.stringLiteral("PDFTextField"),
    defaultValue: core.serialization.string().optional(),
    isPassword: core.serialization.boolean().optional(),
    isRichFormatted: core.serialization.boolean().optional(),
    isScrollable: core.serialization.boolean().optional(),
    isCombed: core.serialization.boolean().optional(),
    isMultiline: core.serialization.boolean().optional(),
    isFileSelector: core.serialization.boolean().optional(),
    maxLength: core.serialization.number().optional(),
});

export declare namespace FormDetectResponseItemDefaultValue {
    interface Raw {
        type: "PDFTextField";
        defaultValue?: string | null;
        isPassword?: boolean | null;
        isRichFormatted?: boolean | null;
        isScrollable?: boolean | null;
        isCombed?: boolean | null;
        isMultiline?: boolean | null;
        isFileSelector?: boolean | null;
        maxLength?: number | null;
    }
}
