/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { FormFillRequestOptionsFieldsItemTwoType } from "./FormFillRequestOptionsFieldsItemTwoType";

export const FormFillRequestOptionsFieldsItemTwo: core.serialization.ObjectSchema<
    serializers.pdf.FormFillRequestOptionsFieldsItemTwo.Raw,
    Fileforge.pdf.FormFillRequestOptionsFieldsItemTwo
> = core.serialization.object({
    type: FormFillRequestOptionsFieldsItemTwoType,
    selected: core.serialization.list(core.serialization.string()),
});

export declare namespace FormFillRequestOptionsFieldsItemTwo {
    interface Raw {
        type: FormFillRequestOptionsFieldsItemTwoType.Raw;
        selected: string[];
    }
}
