/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FileforgeEnvironment = {
    Default: "https://api.fileforge.com",
} as const;

export type FileforgeEnvironment = typeof FileforgeEnvironment.Default;
