/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FileforgeEnvironment = {
  Default: "https://97e3e2564136.ngrok.app",
} as const;

export type FileforgeEnvironment = typeof FileforgeEnvironment.Default;
