/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as Fileforge from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { FormDetectResponseItem } from "../types/FormDetectResponseItem";

export const Response: core.serialization.Schema<
    serializers.pdf.form.detect.Response.Raw,
    Fileforge.pdf.FormDetectResponseItem[]
> = core.serialization.list(FormDetectResponseItem);

export declare namespace Response {
    type Raw = FormDetectResponseItem.Raw[];
}
