/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../../index";

/**
 * @example
 *     {}
 */
export interface FormMarkRequest {
    options?: Fileforge.pdf.FormMarkRequestOptions;
}
