/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Fileforge from "../../../../api/index";
import * as core from "../../../../core";

export const PdfInsertRequestOptions: core.serialization.ObjectSchema<
    serializers.PdfInsertRequestOptions.Raw,
    Fileforge.PdfInsertRequestOptions
> = core.serialization.object({
    insertPage: core.serialization.number(),
});

export declare namespace PdfInsertRequestOptions {
    interface Raw {
        insertPage: number;
    }
}
