/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Fileforge from "../../../../api/index";
import * as core from "../../../../core";

export const PdfMergeRequestOptions: core.serialization.ObjectSchema<
    serializers.PdfMergeRequestOptions.Raw,
    Fileforge.PdfMergeRequestOptions
> = core.serialization.object({
    host: core.serialization.boolean().optional(),
    expiresAt: core.serialization.date().optional(),
    fileName: core.serialization.string().optional(),
    allowViewing: core.serialization.boolean().optional(),
});

export declare namespace PdfMergeRequestOptions {
    interface Raw {
        host?: boolean | null;
        expiresAt?: string | null;
        fileName?: string | null;
        allowViewing?: boolean | null;
    }
}
