/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Fileforge from "../../../../api/index";
import * as core from "../../../../core";

export const PdfMergeRequestOptions: core.serialization.ObjectSchema<
    serializers.PdfMergeRequestOptions.Raw,
    Fileforge.PdfMergeRequestOptions
> = core.serialization.object({});

export declare namespace PdfMergeRequestOptions {
    interface Raw {}
}
