/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FormDetectResponseItemIsMutuallyExclusive {
    type: "PDFRadioGroup";
    options?: string[];
    selected?: string;
    isMutuallyExclusive?: boolean;
    isOffToggleable?: boolean;
}
