/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../index";

export type FormFillRequestOptionsFieldsItem =
    | Fileforge.pdf.FormFillRequestOptionsFieldsItemValue
    | Fileforge.pdf.FormFillRequestOptionsFieldsItemChecked
    | Fileforge.pdf.FormFillRequestOptionsFieldsItemTwo
    | Fileforge.pdf.FormFillRequestOptionsFieldsItemThree;
