/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../index";

export interface FormFillRequestOptions {
    /** Fields to fill or change in the PDF document. */
    fields: Fileforge.pdf.FormFillRequestOptionsFieldsItem[];
}
