/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FormDetectResponseItemDefaultValue {
    type: "PDFTextField";
    defaultValue?: string;
    isPassword?: boolean;
    isRichFormatted?: boolean;
    isScrollable?: boolean;
    isCombed?: boolean;
    isMultiline?: boolean;
    isFileSelector?: boolean;
    maxLength?: number;
}
