/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormFillRequestOptionsFieldsItemTwoType = "PDFOptionList" | "PDFDropdown";

export const FormFillRequestOptionsFieldsItemTwoType = {
    PdfOptionList: "PDFOptionList",
    PdfDropdown: "PDFDropdown",
} as const;
