/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../index";

export interface FormFillRequestOptions {
    /** Flatten the form fields after filling them. This will make the PDF form uneditable. */
    flattenForm?: boolean;
    /** Fields to fill or change in the PDF document. */
    fields: Fileforge.pdf.FormFillRequestOptionsFieldsItem[];
}
