/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FormDetectResponseItemIsEditableType = "PDFDropdown" | "PDFOptionList";

export const FormDetectResponseItemIsEditableType = {
    PdfDropdown: "PDFDropdown",
    PdfOptionList: "PDFOptionList",
} as const;
