/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../index";

export type FormDetectResponseItem =
    | Fileforge.pdf.FormDetectResponseItemIsChecked
    | Fileforge.pdf.FormDetectResponseItemIsEditable
    | Fileforge.pdf.FormDetectResponseItemIsMutuallyExclusive
    | Fileforge.pdf.FormDetectResponseItemDefaultValue;
