/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../index";

export interface FormDetectResponseItemIsEditable {
    type: Fileforge.pdf.FormDetectResponseItemIsEditableType;
    options?: string[];
    isMultiselect?: boolean;
    selected?: string[];
    isEditable?: boolean;
}
