/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fileforge from "../../../../../index";

export interface FormDetectRequestOptions {
    aiDetection?: Fileforge.pdf.FormDetectRequestOptionsAiDetection;
}
