/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PdfExtractRequestOptions {
    /** The page number to split the document at */
    start: number;
    /** The page number to split the document at */
    end: number;
}
