/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Conversion options. This field is required even if empty.
 *
 * **Options**
 *
 * - `templateLiterals`: Map of template literals to replace in the document. Template literals should be enclosed in double curly braces, e.g. `{{name}}`. Variables name can contain alphanumeric characters and hyphens. All variables are case-sensitive. The value for each variable should be a string. If a value of undefined is passed, the variable will not be removed from the document. If you need to remove a variable, pass an empty string as the value.
 *
 * **NB** variables should **not** have surrounding spaces, e.g. `{{ name }}`.
 *
 * **Example**
 *
 * In the Word document: `{{name}} {{nickname}}. was born on {{date}}.`
 *
 * ```json
 * {
 *   "templateLiterals": {
 *     "name": "John Doe",
 *     "date": "2021-12-31",
 *     "nickname": ""
 *   }
 * }
 * ```
 *
 * There will not be an error if a variable is not found in the document, nor if variables found in the document are not in the options.
 */
export interface PdfFromDocxRequestOptions {
    /** Whether to keep the text formatting of the variables in the document. Default is true. */
    keepOriginalStyles?: boolean;
    /** Map of template literals to replace in the document. */
    templateLiterals?: Record<string, string>;
}
