/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PdfSplitRequestOptions {
    /** The page number to split the document at (the page will be included in the first document) */
    splitPage: number;
}
