/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Fileforge from "../index";

export class UnauthorizedError extends errors.FileforgeError {
    constructor(body: Fileforge.ErrorSchema) {
        super({
            message: "UnauthorizedError",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnauthorizedError.prototype);
    }
}
