/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Fileforge from "../../api/index";
import * as core from "../../core";

export const ErrorSchema: core.serialization.ObjectSchema<serializers.ErrorSchema.Raw, Fileforge.ErrorSchema> =
    core.serialization.object({
        statusCode: core.serialization.number(),
        code: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace ErrorSchema {
    interface Raw {
        statusCode: number;
        code: string;
        message: string;
    }
}
