/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Fileforge from "../../api/index";
import * as core from "../../core";

export const GetStatusResponse: core.serialization.ObjectSchema<
    serializers.GetStatusResponse.Raw,
    Fileforge.GetStatusResponse
> = core.serialization.object({
    status: core.serialization.string().optional(),
});

export declare namespace GetStatusResponse {
    interface Raw {
        status?: string | null;
    }
}
